### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by AntoVie** [sebw/pushtify#4]
I've installed pushtify with this : 
```
  services:
    pushtify:
      image: ghcr.io/sebw/pushtify:latest
      container_name: pushtify
      environment:
        - GOTIFY_TOKEN=Ai_XXXXXXXX_
        - GOTIFY_HOST=192.168.2.221:8079
        - PUSHOVER_USERKEY=uzXXXXXXXh4
      restart: unless-stopped
```
The build goes well then in the container logs I got this message : 
```
[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)
### closed ###
```

Do we need to use the ssl connection to Gotify ? Because I didn't enable it in Gotify.

Thanks
