### ISSUE TITLE
Pushtify container keeps restarting

### ISSUE THREAD

**Issue by McRam** [sebw/pushtify#6]
Hello,

I amtrying to integrate Gotify with Pushover but my Pushtify docker container keeps on starting and stopping. Log looks like this:

```
Container started
[Errno -3] Try again
### closed ###
Container stopped
Etc.
```

Pushtify was created with a docker compose file. Content is:

```
  pushtify:
    container_name: pushtify
    hostname: pushtify
    image: ghcr.io/sebw/pushtify:latest
    environment:
      - PGID=0
      - PUID=0
      - GOTIFY_TOKEN=xxx
      - GOTIFY_HOST=gotify
      - PUSHOVER_USERKEY=yyy
    network_mode: 'bridge'
    restart: unless-stopped
```

Gotify is running on the same host as Pushtify without any problems and is using port 80. No clue as to what I am doing wrong. The restarting seems to point to a websocket problem if I read the Pushtify documentation correctly. Please help me resolve this. Thanks in advance.
